---

env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - double
  semi:
  - error
  - always
  no-unused-vars: off
  no-console: off
settings:
  import/core-modules: [ aws-sdk ]